name: Feature Request
description: Request a feature.
type: Feature
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature you want
      description: It's better that you also provide your use case.
    validations:
      required: true
